yarnPath: ".yarn/releases/yarn-berry.cjs"

cacheFolder: ./.yarn/offline-cache

logFilters:
  - code: YN0005
    level: discard
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0061
    level: discard
  - code: YN0062
    level: discard
  - code: YN0063
    level: discard
  - code: YN0076
    level: discard

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x86
    - x64
    - ia32
    - arm
    - arm64
  os:
    - current
    - darwin
    - linux
    - win32
