name: Check

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: yarn install --immutable --immutable-cache

      - name: Build
        run: yarn build

      - name: Check types
        run: yarn check-types

      - name: Tests
        run: yarn run test --coverage

      - name: Upload coverage reports to Codecov
        if: matrix.node-version == '18.x'
        uses: codecov/codecov-action@v3
        with:
          directory: "./coverage"
          token: ${{ secrets.CODECOV_TOKEN }}
