name: Copyright

on:
  # Runs on merge to master branch or manual dispatching
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Run the action to add copyright text to files
      - name: Add Copyright Comment
        uses: alizeait/ts-copyright-action@v1
        with:
          copyright: Copyright (c) 2023 Ali Zeaiter.\nThis source code is licensed under the MIT license found in the\nLICENSE file in the root directory of this source tree.
          exclude: "fixtures/**,dist/**,node_modules/**,src/tests/**"

      # Open a pull request with changed files
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Add copyright comment to files
          title: Add Copyright Comment to Files
          body: Update Copyright text
